server:
  port: 8085

spring:
  application:
    name: file-upload-service
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

file:
  upload:
    directory: ./uploads

aws:
  s3:
    enabled: false
    bucket-name: hyderabadinfra-files
  access-key-id: ${AWS_ACCESS_KEY_ID:}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
  region: ${AWS_REGION:us-east-1}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.hyderabadinfra.fileupload: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"