server:
  port: 8084

spring:
  application:
    name: user-history-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-service
    username: inventory_service
    password: password
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: user-history-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
          userActivity:com.hyderabadinfra.common.events.UserActivityEvent,
          propertyCreated:com.hyderabadinfra.common.events.PropertyEvents$PropertyCreatedEvent,
          propertyViewed:com.hyderabadinfra.common.events.PropertyEvents$PropertyViewedEvent,
          propertySearched:com.hyderabadinfra.common.events.PropertyEvents$PropertySearchedEvent
  
  redis:
    host: localhost
    port: 6379
    database: 3
    timeout: 2000ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.hyderabadinfra.userhistory: DEBUG
    org.springframework.kafka: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# CQRS Configuration
cqrs:
  event-store:
    table-name: event_store
  read-model:
    cache-ttl: 300 # 5 minutes
  
# Service Discovery for RestTemplate
services:
  user-management:
    url: http://localhost:8081
  property-management: 
    url: http://localhost:8082
  search-service:
    url: http://localhost:8083