server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/auth/**, /api/users/**
          
        - id: property-service
          uri: http://property-service:8082
          predicates:
            - Path=/api/properties/**, /api/public/properties/**
          
        - id: search-service
          uri: http://search-service:8083
          predicates:
            - Path=/api/search/**, /api/public/search/**
          
        - id: notification-service
          uri: http://notification-service:8084
          predicates:
            - Path=/api/notifications/**
          
        - id: file-service
          uri: http://file-service:8085
          predicates:
            - Path=/api/files/**
  
  redis:
    host: ${REDIS_HOST:redis}
    port: 6379
    database: 0
    timeout: 2000ms

jwt:
  secret: ${JWT_SECRET:hyderabadinfra-secret-key}
  expiration: ${JWT_EXPIRATION:86400}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION:604800}