server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**, /api/auth/**
        - id: property-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/properties/**
        - id: search-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/search/**
        - id: user-history-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/user-history/**
        - id: notification-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/notifications/**
        - id: file-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/files/**
  
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 2000ms

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.hyderabadinfra.gateway: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

jwt:
  secret: hyderabadinfra-secret-key
  expiration: 86400
  refresh:
    expiration: 604800